---
- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Start Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: Add Prometheus data source to Grafana
  uri:
    url: "http://localhost:3000/api/datasources"
    method: POST
    user: admin
    password: admin
    body: |
      {
        "name":"Prometheus",
        "type":"prometheus",
        "url":"http://prometheus:9090",
        "access":"proxy",
        "isDefault":true
      }
    body_format: json
    headers:
      Content-Type: "application/json"
    status_code: 200

- name: Create DevOps Academy organization
  uri:
    url: "http://localhost:3000/api/orgs"
    method: POST
    user: admin
    password: admin
    body: |
      {
        "name":"DevOps Academy"
      }
    body_format: json
    headers:
      Content-Type: "application/json"
    status_code: 200

- name: Import Dashboard
  uri:
    url: "http://localhost:3000/api/dashboards/import"
    method: POST
    user: admin
    password: admin
    body: "{{ lookup('file', 'dashboard.json') }}"
    body_format: json
    headers:
      Content-Type: "application/json"
    status_code: 200
